#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : hdmedians
Version  : 0.13
Release  : 1
URL      : https://files.pythonhosted.org/packages/df/19/b8c304859fa12a71eeadd2e90a7f19000c3f1281be370f035a9fce3b014f/hdmedians-0.13.tar.gz
Source0  : https://files.pythonhosted.org/packages/df/19/b8c304859fa12a71eeadd2e90a7f19000c3f1281be370f035a9fce3b014f/hdmedians-0.13.tar.gz
Summary  : High-dimensional medians
Group    : Development/Tools
License  : GPL-3.0
Requires: hdmedians-python = %{version}-%{release}
Requires: hdmedians-python3 = %{version}-%{release}
Requires: Cython
Requires: numpy
BuildRequires : Cython
BuildRequires : buildreq-distutils3
BuildRequires : nose
BuildRequires : numpy

%description
No detailed description available

%package python
Summary: python components for the hdmedians package.
Group: Default
Requires: hdmedians-python3 = %{version}-%{release}

%description python
python components for the hdmedians package.


%package python3
Summary: python3 components for the hdmedians package.
Group: Default
Requires: python3-core

%description python3
python3 components for the hdmedians package.


%prep
%setup -q -n hdmedians-0.13

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1556217329
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
