#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : hdmedians
Version  : 0.14
Release  : 8
URL      : https://files.pythonhosted.org/packages/6c/20/d2c8999f621bd4178fa4c9f9634d488f7b4271f615cd60e432a92c4cbf9d/hdmedians-0.14.tar.gz
Source0  : https://files.pythonhosted.org/packages/6c/20/d2c8999f621bd4178fa4c9f9634d488f7b4271f615cd60e432a92c4cbf9d/hdmedians-0.14.tar.gz
Summary  : High-dimensional medians
Group    : Development/Tools
License  : Apache-2.0
Requires: hdmedians-python = %{version}-%{release}
Requires: hdmedians-python3 = %{version}-%{release}
Requires: Cython
Requires: numpy
BuildRequires : Cython
BuildRequires : buildreq-distutils3
BuildRequires : nose
BuildRequires : numpy

%description
# Hdmedians
Did you know there is no unique way to mathematically extend the concept of a
[median](https://en.wikipedia.org/wiki/Median) to higher dimensions?

%package python
Summary: python components for the hdmedians package.
Group: Default
Requires: hdmedians-python3 = %{version}-%{release}

%description python
python components for the hdmedians package.


%package python3
Summary: python3 components for the hdmedians package.
Group: Default
Requires: python3-core

%description python3
python3 components for the hdmedians package.


%prep
%setup -q -n hdmedians-0.14
cd %{_builddir}/hdmedians-0.14

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1601050270
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
